### ISSUE TITLE
TODO pour un travail bien fait

### ISSUE THREAD

**Issue by anaisxantippe** [anaisxantippe/skydrone.github.io#10]
Ajoutez ici les détails de post production qui nécessitent une correction/ un ajustement  ou qui ne fonctionnent juste pas

- [x] Syntaxe de la regex de mot de passe à changer
- [ ] Bouton "déconnexion" n'est pas centré 
![image](https://user-images.githubusercontent.com/77981364/123781080-1ad89500-d8d4-11eb-8e05-7f53499f80a4.png)
- [ ] .
- [ ] .
- [ ] Panel utilisateur ; encarts d'information pourraient avoir une couleur beaucoup plus neutre.
- [ ] La plupart des boutons de crud sont invisibles.
- [x] Le CRUD de création de compte ResourceDepartment ne fonctionne pas
- [ ] .
- [ ] .
- [ ] .
- [ ] .
- [ ] .
