### ISSUE TITLE
TODO GÉNÉRALE

### ISSUE THREAD

**Issue by anaisxantippe** [anaisxantippe/skydrone.github.io#2]
### **Back end :** 
0% ⬜⬜⬜⬜⬜⬜⬜⬜⬜⬛ 100%

_Base de données :_
- [x] Extraire les informations essentielles du CDC | Fabien & Anaïs
- [x] Faire le schéma entité - association (looping) | Fabien & Anaïs
- [x] Générer le SQL, vérifier sa syntaxe et l'ajouter à Heidi | Fabien & Anaïs
- [ ] Remplir le contenu de la base (11 tables)
__________________________________________________________
_Symfony :_
- [x] Initialiser le squelette projet avec Symfony | Fabien
- [x] Réaliser un CRUD sur la table 'product' | Anaïs
- [x] Réaliser un CRUD sur la table 'user' | Juliette
- [x] Réaliser un CRUD sur la table 'orders' | Fabien
- [x] Réaliser un CRUD sur la table 'opinions' | Alexandre
- [x] Réaliser un CRUD sur la table 'bill' | Anaïs
- [x] Réaliser un CRUD sur la table 'delivery_form' | Anaïs
- [ ] Vérifications des formulaires | tout le monde
- [x] Réaliser un panier /!\ | Anaïs
- [x] page d'accueil /!\  | Juliette
- [x] page de contact | Anaïs
- [x] Sessions /!\ | Fabien
- [x] Recherche simple + avancée | Fabien
- Réaliser un CRUD sur le panel | Fabien
   - [x] Panel client
   - [x] Panel service commercial
   - [x] Panel service fournisseurs
   - [x] Panel direction

> FINIR LE BACK POUR MERCREDI MATIN

___________________________________________________________________________________

### **Front end :**
0% ⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛ 100%

- [x] Squelette (navbar, footer, organisation des éléments entre deux) | Juliette
- [x] Page d'accueil | Juliette
- Panels (dashboards) | Anaïs
   - [x] Panel client 
   - [x] Panel service commercial 
   - [x] Panel service fournisseur
   - [x] Panel direction
- Catalogue | Anaïs -> Ju prend la main ?
   - [x] Catalogue global 
   - [ ] Détail des produits
   - [ ] Ajout de produits
   - [ ] Modification de produits
- [ ] Panier | Anaïs
- Commandes | (Alex)
   - [ ] Consulter les commandes
   - [ ] Détails d'une commande
   - [ ] Modification d'une commande
- [ ] Page de contact | Alexandre
- Avis client | Alexandre
   - [ ] Consulter les avis
   - [ ] Ajout d'un avis
   - [ ] Modification d'un avis
- Facture |
   - [ ] Consulter la facture
   - [ ] Ajout d'une facture
   - [ ] Modification d'une facture
   - [ ] Suppression d'une facture
- Bon de livraison |
   - [ ] Consulter un bon de livraison
   - [ ] Ajout d'un bon de livraison
   - [ ] Modification d'un bon de livraison
   - [ ] Suppression d'un bon de livraison
- Users et détails des comptes |
   - [ ] Consulter son profil
   - [ ] Ajout d'un nouveau profil
   - [ ] Modification du profil
   - [ ] Suppression d'un profil
_________________________________________________________________
Bonus pour gagner des points de style :
- [ ] Page "à propos" | 
- [ ] Page 404 | Anaïs
- [ ]  |
